In [1]:
#importing libraries
from keras import Sequential
from keras.layers import Dense, SimpleRNN
import numpy as np

In [2]:
#defining Simple RNN model

model=Sequential()
model.add(SimpleRNN(4,input_shape=(4,5)))
model.add(Dense(1, activation="sigmoid"))

In [3]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 4)                 40        
                                                                 
 dense (Dense)               (None, 1)                 5         
                                                                 
Total params: 45 (180.00 Byte)
Trainable params: 45 (180.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [4]:
model.get_weights()

[array([[ 0.15366352,  0.2736677 , -0.10614657,  0.78891623],
        [-0.46641508, -0.14458144,  0.5550871 ,  0.7117659 ],
        [ 0.2591741 , -0.38944688, -0.43897566, -0.7825259 ],
        [-0.25195622,  0.5097766 , -0.41960388, -0.6664956 ],
        [ 0.7390598 , -0.546679  ,  0.6738398 , -0.11929232]],
       dtype=float32),
 array([[-0.21280253,  0.0537166 , -0.67744213, -0.7020696 ],
        [ 0.78492665,  0.09884065,  0.30857927, -0.52810943],
        [ 0.02599343, -0.9912208 ,  0.04077092, -0.12305934],
        [-0.5813171 ,  0.06947399,  0.6664748 , -0.4615789 ]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[-0.01883256],
        [ 0.25086617],
        [-0.4128607 ],
        [ 0.6973082 ]], dtype=float32),
 array([0.], dtype=float32)]

In [5]:
model.get_weights()[0]

array([[ 0.15366352,  0.2736677 , -0.10614657,  0.78891623],
       [-0.46641508, -0.14458144,  0.5550871 ,  0.7117659 ],
       [ 0.2591741 , -0.38944688, -0.43897566, -0.7825259 ],
       [-0.25195622,  0.5097766 , -0.41960388, -0.6664956 ],
       [ 0.7390598 , -0.546679  ,  0.6738398 , -0.11929232]],
      dtype=float32)

In [6]:
model.get_weights()[0].shape

(5, 4)

In [7]:
model.get_weights()[1]

array([[-0.21280253,  0.0537166 , -0.67744213, -0.7020696 ],
       [ 0.78492665,  0.09884065,  0.30857927, -0.52810943],
       [ 0.02599343, -0.9912208 ,  0.04077092, -0.12305934],
       [-0.5813171 ,  0.06947399,  0.6664748 , -0.4615789 ]],
      dtype=float32)

In [8]:
model.get_weights()[1].shape

(4, 4)

In [9]:
from keras.datasets import imdb

In [10]:
(X_train,y_train),(X_test,y_test)=imdb.load_data()

In [11]:
len(X_train[0])

218

In [12]:
len(X_train[1])

189

In [13]:
len(X_train[2])

141

In [14]:
mylist=[]
for review in X_train:
  mylist.append(len(review))
min(mylist)

11

In [15]:
X_train.shape

(25000,)

In [16]:
X_test.shape

(25000,)

In [17]:
sent=[
      "india won worldcup",
      "rohit played very well",
      "above all is my imagination",
      "bharat mata ki jay",
      "definatly we goona win next worldcup"
]

In [18]:
sent

['india won worldcup',
 'rohit played very well',
 'above all is my imagination',
 'bharat mata ki jay',
 'definatly we goona win next worldcup']

In [19]:
# it is performing integer encoding
from keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()

In [20]:
tokenizer.fit_on_texts(sent)

In [21]:
tokenizer.word_index

{'worldcup': 1,
 'india': 2,
 'won': 3,
 'rohit': 4,
 'played': 5,
 'very': 6,
 'well': 7,
 'above': 8,
 'all': 9,
 'is': 10,
 'my': 11,
 'imagination': 12,
 'bharat': 13,
 'mata': 14,
 'ki': 15,
 'jay': 16,
 'definatly': 17,
 'we': 18,
 'goona': 19,
 'win': 20,
 'next': 21}

In [22]:
tokenizer.word_counts

OrderedDict([('india', 1),
             ('won', 1),
             ('worldcup', 2),
             ('rohit', 1),
             ('played', 1),
             ('very', 1),
             ('well', 1),
             ('above', 1),
             ('all', 1),
             ('is', 1),
             ('my', 1),
             ('imagination', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 1),
             ('jay', 1),
             ('definatly', 1),
             ('we', 1),
             ('goona', 1),
             ('win', 1),
             ('next', 1)])

In [23]:
tokenizer.document_count

5

In [24]:
encoding=tokenizer.texts_to_sequences(sent)

In [25]:
encoding

[[2, 3, 1],
 [4, 5, 6, 7],
 [8, 9, 10, 11, 12],
 [13, 14, 15, 16],
 [17, 18, 19, 20, 21, 1]]

In [26]:
from keras.utils import pad_sequences

In [27]:
pad_sequences(encoding ,padding="post")

array([[ 2,  3,  1,  0,  0,  0],
       [ 4,  5,  6,  7,  0,  0],
       [ 8,  9, 10, 11, 12,  0],
       [13, 14, 15, 16,  0,  0],
       [17, 18, 19, 20, 21,  1]], dtype=int32)

In [28]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [29]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [30]:
X_train=pad_sequences(X_train ,padding="post",maxlen=50)
X_test=pad_sequences(X_test ,padding="post",maxlen=50)

In [31]:
model=Sequential()
model.add(SimpleRNN(32,input_shape=(50,1)))
model.add(Dense(1,activation="sigmoid"))

In [32]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [33]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [34]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=5)

Epoch 1/5
782/782 [==============================] - 16s 17ms/step - loss: 0.6955 - accuracy: 0.5058 - val_loss: 0.6939 - val_accuracy: 0.5050
Epoch 2/5
782/782 [==============================] - 13s 17ms/step - loss: 0.6930 - accuracy: 0.5062 - val_loss: 0.6942 - val_accuracy: 0.5040
Epoch 3/5
782/782 [==============================] - 13s 16ms/step - loss: 0.6929 - accuracy: 0.5124 - val_loss: 0.6941 - val_accuracy: 0.5056
Epoch 4/5
782/782 [==============================] - 13s 17ms/step - loss: 0.6928 - accuracy: 0.5080 - val_loss: 0.6943 - val_accuracy: 0.5027
Epoch 5/5
782/782 [==============================] - 14s 18ms/step - loss: 0.6932 - accuracy: 0.5017 - val_loss: 0.6959 - val_accuracy: 0.5067


In [35]:
model.predict(X_test)

782/782 [==============================] - 4s 5ms/step


array([[0.5408047],
       [0.5408047],
       [0.5408047],
       ...,
       [0.5408047],
       [0.5408047],
       [0.5408047]], dtype=float32)

In [36]:
loss,accuracy=model.evaluate(X_test,y_test)

782/782 [==============================] - 5s 6ms/step - loss: 0.6959 - accuracy: 0.5067


In [37]:
loss

0.6959342956542969

In [38]:
accuracy

0.5066800117492676